import { IBook } from "../types";
import obyknovennaya_istoriya from "../assets/images/obyknovennaya_istoriya.jpg";
import o_detyah_koscheevyh from "../assets/images/o_detyah_koscheevyh.jpg";
import spasenie_dikogo_robota from "../assets/images/spasenie_dikogo_robota.jpg";
import temnaya_storona_srednevekovoy_yaponii from "../assets/images/temnaya_storona_srednevekovoy_yaponii.jpg";
import snezhnaya_koroleva from "../assets/images/snezhnaya_koroleva.jpg";
import Nyryaa_v_sinevy_nebes from "../assets/images/Nyryaa_v_sinevy_nebes.jpg";
import volshebnik_izumrudnogo_goroda from '../assets/images/volshebnik_izumrudnogo_goroda.jpg';
import vnutrennyaya_opora from "../assets/images/vnutrennyaya_opora.jpg";
import devushka_so_snezhnum_serdzem from '../assets/images/devushka_so_snezhnum_serdzem.jpg';
import esteticheskii_intellect from '../assets/images/esteticheskii_intellect.jpg';
import legendy_y_mifi_drevney_grezii from '../assets/images/legendy_y_mifi_drevney_grezii.jpg';
import poterayl_slepoi_dudu from '../assets/images/poterayl_slepoi_dudu.jpg';
import skazy from '../assets/images/skazy.jpg';
import tymur_y_ego_komanda from '../assets/images/tymur_y_ego_komanda.jpg';
import volshebnaya_biblioteka_brokkoli from '../assets/images/volshebnaya_biblioteka_brokkoli.jpg';
import Dar from '../assets/images/Dar.png';
import immunitet_k_vygoraniu from '../assets/images/immunitet_k_vygoraniu.png';
import toksychnye_kollegy from '../assets/images/toksychnye_kollegy.png';
import Spokoinoe_serdze from '../assets/images/Spokoinoe_serdze.png';

export const BOOKS: IBook[] = [
  {
    title: "О детях кощеевых",
    author: "А.Селютина",
    description:
      "Продолжение фэнтези на основе русских народных сказок 'И жили они долго и счастливо'",
    audio: true,
    ebook: true,
    paperbook: true,
    price: "809 Р",
    new: true,
    availability: true,
    image: o_detyah_koscheevyh,
    genre: "Детство",
  },
  {
    title: "Спасение дикого робота",
    author: "П.Браун",
    description: "Продолжение приключений робота по имени Роз",
    audio: true,
    ebook: true,
    paperbook: true,
    price: "463 Р",
    new: false,
    availability: true,
    image: spasenie_dikogo_robota,
    genre: "Проза",
  },
  {
    title: "Темная сторона средневековой Японии",
    author: "Д.Кикнадзе",
    description:
      "Японская повседневность эпохи Хэйан, самураи, потусторонний мир и буддийский ад",
    audio: true,
    ebook: true,
    paperbook: true,
    price: "548 Р",
    new: false,
    availability: true,
    image: temnaya_storona_srednevekovoy_yaponii,
    genre: "Культура",
  },
  {
    title: "Ныряя в синеву небес",
    author: "Ринга Ли",
    description: "Популярная новелла в оформлении Eornheit и huaepiphany",
    audio: true,
    ebook: true,
    paperbook: true,
    price: "1297 Р",
    new: true,
    availability: true,
    image: Nyryaa_v_sinevy_nebes,
    genre: "Культура",
  },
    {
      title: "Внутренняя опора",
      author: "Анна Бабич",
      description: "56 точек опоры для обретения внутренней гармонии",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "373 Р",
      new: true,
      availability: true,
      image: vnutrennyaya_opora,
      genre: "Саморазвитие",
    },
    {
      title: "Волшебник изумрудного города",
      author: "А.Волков",
      description: "Классика детской литературы в современном оформлении",
      audio: false,
      ebook: false,
      paperbook: true,
      price: "238 Р",
      new: true,
      availability: true,
      image: volshebnik_izumrudnogo_goroda,
      genre: "Детство",
    },
    {
      title: "Волшебная бибилиотека брокколи",
      author: "Ли Юнхи",
      description: "Детское фэнтези про таинственную библиотеку и волшебные превращения",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "373 Р",
      new: true,
      availability: true,
      image: volshebnaya_biblioteka_brokkoli,
      genre: "Детство",
    },
    {
      title: "Тимур и его команда",
      author: "А.Гайдар",
      description: "Три знаменитые повести о Тимуре под одной обложкой",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "238 Р",
      new: false,
      availability: true,
      image: tymur_y_ego_komanda,
      genre: "Детство",
    },
    {
      title: "Сказы",
      author: "П.Бажов",
      description: "Произведения школьной программы в современном оформлении",
      audio: false,
      ebook: false,
      paperbook: true,
      price: "238 Р",
      new: true,
      availability: true,
      image: skazy,
      genre: "Детство",
    },
    {
      title: "Потерял слепой дуду",
      author: "А.Григоренко",
      description: "Сильная и глубокая повесть о вечных ценностях",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "",
      new: false,
      availability: true,
      image: poterayl_slepoi_dudu,
      genre: "Лайфстайл",
    },
    {
      title: "Легенды и мифы Древней Греции",
      author: "Н.Кун",
      description: "Увлекательный пересказ греческой мифологии в современном оформлении",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "238 Р",
      new: true,
      availability: true,
      image: legendy_y_mifi_drevney_grezii,
      genre: "Культура",
    },
    {
      title: "Эстетический интеллект",
      author: "Полин Браун",
      description: "Принципы эстетического интеллекта для развития бизнеса",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "598 Р",
      new: false,
      availability: true,
      image: esteticheskii_intellect,
      genre: "Бизнес",
    },
    {
      title: "Девушка со снежным сердцем",
      author: "Loputyn",
      description: "Старинная японская легенда в прочтении художницы Loputyn",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "498 Р",
      new: false,
      availability: true,
      image: devushka_so_snezhnum_serdzem,
      genre: "Культура",
    },
    {
      title: "Дар",
      author: "Эдит Ева Эгер",
      description: "12 ключей к внутреннему освобождению и обретению себя",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "698 Р",
      new: false,
      availability: true,
      image: Dar,
      genre: "Психология",
    },
    {
      title: "Иммунитет к выгоранию",
      author: "Канди Винс",
      description: "Эмоциональный интеллект для продуктивной работы без срывов",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "473 Р",
      new: false,
      availability: true,
      image: immunitet_k_vygoraniu,
      genre: "Здоровье",
    },
    {
      title: "Токсичные коллеги",
      author: "Тесса Уэст",
      description: "Как работать с невыносимыми людьми",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "488 Р",
      new: false,
      availability: true,
      image: toksychnye_kollegy,
      genre: "Научпоп",
    },
    {
      title: "Спокойное сердце",
      author: "Накамура Цунэко",
      description: "О счастье принятия и умении идти дальше. Обнимающая мудрость психотерапевта Накамура-сенсея",
      audio: true,
      ebook: true,
      paperbook: true,
      price: "348 Р",
      new: false,
      availability: true,
      image: Spokoinoe_serdze,
      genre: "Творчество",
    },
    {
      title: "Обыкновенная история",
      author: "И.Гончаров",
      description: "Захватывающий и остроумный дебютный роман Ивана Гончарова",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "387 Р",
      new: true,
      availability: true,
      image: obyknovennaya_istoriya,
      genre: "Проза",
    },
    {
      title: "Снежная королева",
      author: "Г.Х.Андерсон",
      description:
        "Самая популярная сказка Андерсена в нежных акварельных иллюстрациях Оксаны Викторовой",
      audio: false,
      ebook: true,
      paperbook: true,
      price: "747 Р",
      new: true,
      availability: true,
      image: snezhnaya_koroleva,
      genre: "Детство",
    },
    // {
    //   title: "",
    //   author: "",
    //   description: "",
    //   audio: true,
    //   ebook: true,
    //   paperbook: true,
    //   price: "",
    //   new: true,
    //   availability: true,
    //   image: '../assets/images/',
    //   genre: "",
    // },
];
