export {
  CONTENT_FOOTER_NAVIGATION,
  CONTENT_FOOTER_SOCIALS,
  CONTENT_FOOTER_PAYMENTS,
  CONTENT_FOOTER_CONTACTS,
} from "./contentFooterLinks";
export {
  CONTENT_HEADER_NAVIGATION,
  CONTENT_HEADER_NAVIGATION_SVG,
} from "./contentHeaderNavigation";
